<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325102109 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE daily_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, calories_goal INT NOT NULL, date DATE NOT NULL, owner_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B489D9C97E3C61F9 ON daily_logs (owner_id)');
        $this->addSql('CREATE TABLE product_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity DOUBLE PRECISION NOT NULL, product_id INT DEFAULT NULL, daily_log_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FC21A8754584665A ON product_entries (product_id)');
        $this->addSql('CREATE INDEX IDX_FC21A8756B596A2A ON product_entries (daily_log_id)');
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, brand VARCHAR(255) DEFAULT NULL, barcode INT DEFAULT NULL, size DOUBLE PRECISION NOT NULL, serving_size DOUBLE PRECISION DEFAULT NULL, calories INT NOT NULL, protein DOUBLE PRECISION NOT NULL, carbs DOUBLE PRECISION NOT NULL, fats DOUBLE PRECISION NOT NULL, sugar DOUBLE PRECISION DEFAULT NULL, is_verified BOOLEAN DEFAULT false NOT NULL, unit VARCHAR(255) NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B3BA5A5AB03A8386 ON products (created_by_id)');
        $this->addSql('ALTER TABLE daily_logs ADD CONSTRAINT FK_B489D9C97E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE product_entries ADD CONSTRAINT FK_FC21A8754584665A FOREIGN KEY (product_id) REFERENCES products (id)');
        $this->addSql('ALTER TABLE product_entries ADD CONSTRAINT FK_FC21A8756B596A2A FOREIGN KEY (daily_log_id) REFERENCES daily_logs (id)');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5AB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE daily_logs DROP CONSTRAINT FK_B489D9C97E3C61F9');
        $this->addSql('ALTER TABLE product_entries DROP CONSTRAINT FK_FC21A8754584665A');
        $this->addSql('ALTER TABLE product_entries DROP CONSTRAINT FK_FC21A8756B596A2A');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5AB03A8386');
        $this->addSql('DROP TABLE daily_logs');
        $this->addSql('DROP TABLE product_entries');
        $this->addSql('DROP TABLE products');
    }
}
